site_name: Run Template Orchestrator
repo_url: https://github.com/Cosmo-Tech/run-orchestrator
repo_name: Cosmo-Tech/run-orchestrator
site_description: Cosmo Tech ORC helps with defining and running commands DAG
theme:
  name: material
  logo: assets/logo.png
  font:
    code: Fira Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.footer
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascript/tablesort.js

extra:
  version:
    provider: mike

nav:
  - Home: 
    - Cosmo Tech Run Orchestrator: 'index.md'
    - License: 'License.md'
  - Tutorials:
      - List of tutorials: "tutorial/index.md"
      - My First Orchestrator: "tutorial/first.md"
      - Concerning Configuration: "tutorial/second.md"
      - Brewery: "tutorial/brewery.md"
      - Cloud Ready Simulator: "tutorial/brewery_docker.md"
  - Templates:
      - List of templates: "templates_commands/index.md"
      - "templates_commands/simple_simulation_run.md"
      - "templates_commands/simple_script_run.md"
      - "templates_commands/legacy_run.md"
  - Semantic Validator: "Validator.md"
  - Commands:
      - Commands list: "commands/index.md"
      - Orchestrator: "commands/orchestrator.md"
      - Legacy help:
        - Scenario data download: "commands/scenario_data_downloader.md"
        - Download cloud Steps: "commands/download_cloud_steps.md"
        - Run Python Steps: "commands/run_step.md"
        - Simulation to ADX: "commands/simulation_to_adx.md"
        - Legacy Generator: "commands/legacy_json_generator.md"
      - Helpers:
        - Initialize Parameters folder: "commands/parameters_generator.md"

markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - tables
    - def_list
    - pymdownx.details
    - pymdownx.snippets:
        url_download: true
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            options:
              docstring_style: sphinx
              line_lenth: 120
    - gen-files:
        scripts:
          - scripts/generate_index.py
          - scripts/generate_helps.py
    - literate-nav
    - mike
    - social
    - table-reader