site_name: Run Template Orchestrator
repo_url: https://github.com/Cosmo-Tech/run-orchestrator
repo_name: Cosmo-Tech/run-orchestrator
site_description: Cosmo Tech ORC helps with defining and running commands DAG
theme:
  name: material
  logo: assets/logo.png
  font:
    code: Fira Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.footer
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascript/tablesort.js

extra:
  version:
    provider: mike

nav:
  - Home: 
    - Cosmo Tech Run Orchestrator: 'index.md'
    - License: 'License.md'
    - Dependencies: 'dependencies.md'
  - Tutorials:
      - "tutorial/index.md"
      - "tutorial/getting_started.md"
      - "tutorial/configuration_and_environment.md"
      - "tutorial/cosmotech_simulator.md"
      - "tutorial/advanced_cosmotech_simulator.md"
  - Examples:
      - "examples/index.md"
      - "examples/simple_simulation_run.md"
      - "examples/simple_script_run.md"
      - "examples/legacy_run.md"
      - "examples/git_run.md"
      - "examples/minimal_docker.md"
  - Semantic Validator: "Validator.md"
  - Commands:
      - Orchestrator: 
        - "commands/orchestrator.md"
        - "commands/list_templates.md"
      - Legacy help:
        - "commands/scenario_data_downloader.md"
        - "commands/download_cloud_steps.md"
        - "commands/run_step.md"
        - "commands/simulation_to_adx.md"
        - "commands/legacy_json_generator.md"
      - Helpers:
        - "commands/parameters_generator.md"

not_in_nav: |
  tutorial/brewery_legacy.md

markdown_extensions:
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - tables
    - toc:
        title: "In this page"
        permalink: true
    - def_list
    - pymdownx.details
    - pymdownx.snippets:
        url_download: true
    - pymdownx.superfences
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
    - search:
        lang:
          - en
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            options:
              docstring_style: sphinx
              line_lenth: 120
    - gen-files:
        scripts:
          - scripts/generate_index.py
          - scripts/generate_helps.py
          - scripts/generate_requirements.py
    - literate-nav
    - mike
    - social
    - table-reader

watch:
  - examples
  - partials
  - tutorial