#! /usr/bin/env bash 
CURRENT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
pushd $CURRENT_DIR
echo -n "PROD-13100 - PATH envvar should be passed for further commands as defined"
PATH=$PATH:TEST csm-orc run run.json >/dev/null 2>&1
if [ $? -ne 0 ]; then 
  echo " => FAIL"
  popd
  exit 1
else  
  echo " => SUCCESS"
  popd 
fi