name: issues_unit_tests
on:
  push:
    branches:
      - "main"
  pull_request: 
    types: 
      - opened
      - synchronize
env:
  TERMINAL_WIDTH: "120"
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install -e .[doc]
      - name: run tests
        shell: bash
        run: /bin/bash issues_tests/run_tests