name: Track Dependencies

on:
  push:
    branches:
      - main
      
jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install CycloneDX
        run: |
          python -m pip install --upgrade pip
          python -m pip install cyclonedx-bom
      - name: Install project
        run: |
          python -m venv .venv
          .venv/bin/pip install -r requirements.txt
      - name: Generate SBOM file
        run: |
          cyclonedx-py environment .venv --output-file sbom.json
      - name: Upload cyclonedx bom to dependency
        uses: DependencyTrack/gh-upload-sbom@v3
        with:
          serverhostname: ${{ secrets.DEPENDENCY_TRACK_SERVER_HOSTNAME }}
          apikey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project: '1e001e58-586c-4f01-b5f6-3b94a7c34c43'
          bomfilename: 'sbom.json'
    
